-- VHDL module instantiation generated by SCUBA Diamond (64-bit) 3.2.0.134
-- Module  Version: 5.6
-- Thu Jul 24 19:08:30 2014

-- parameterized module component declaration
component pll_main
    port (CLKI: in  std_logic; CLKOP: out  std_logic; 
        LOCK: out  std_logic);
end component;

-- parameterized module component instance
__ : pll_main
    port map (CLKI=>__, CLKOP=>__, LOCK=>__);
